server:
  port: 8461
spring:
  rabbitmq:
    host: 192.168.1.10
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    virtual-host: /
    # 设置监听为手动应答模式
    listener:
      simple-acknowledge-mode: manual
mail:
  #邮箱服务器地址
  host: smtp.126.com
  #端口
  port: 465
  #邮箱账号
  username: buer_y@126.com
  #smtp授权码
  password: IIPGZAZZDZYAEZEE